version: "3.9"
services:

  rabbitmq:
    image: masstransit/rabbitmq
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbit:/var/lib/rabbitmq

  db:
    image: postgres
    container_name: postgresql-rabbit
    restart: always
    ports:
      - '3462:5432'
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql-rabbit:/var/lib/postgresql/data

volumes:
  rabbit:
  postgresql-rabbit: